### ISSUE TITLE
Error when generating images on CPU

### ISSUE THREAD

**Issue by sdtblck** [rosasalberto/StyleGAN2-TensorFlow-2.x#1]
Hi,

I'm getting the following error when generating images with the CPU - tried on both my home computer (Macbook pro 2013 / Mac OS 10.14.5) and on colab CPUs and getting the same error running the below script, pretty much copied from the example ipynb:

`    """ plot images from generator output """
    # creating random latent vector
    print('Getting seed')
    rnd = np.random.RandomState(seed)
    z = rnd.randn(3, 512).astype('float32')

    # running mapping network
    print('Running mapping network')

    dlatents = gen.mapping_network(z)
    # adjusting dlatents depending on truncation psi, if truncatio_psi = 1, no adjust
    print('Adjusting dlatents')

    dlatents = w_avg + (dlatents - w_avg) * truncation_psi
    # running synthesis network
    print('Running Synthesis network')
    out = gen.synthesis_network(dlatents)

    print('image shape: ', out.shape)

    # converting image/s to uint8
    img = convert_images_to_uint8(out, nchw_to_nhwc=True, uint8_cast=True)

    # plotting images
    img = Image.fromarray(img, 'RGB')
    img.show()`

Error message below - it appears group convolutions can't be run on the CPU? did you ever get CPU inference to work?

`Traceback (most recent call last):
  File "generate.py", line 77, in <module>
    generate_images(generator, seed=96, w_avg=w_average)
  File "generate.py", line 42, in generate_images
    out = gen.synthesis_network(dlatents)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/content/StyleGAN2-TensorFlow-2.x/stylegan2_generator.py", line 103, in call
    x = self.layer_4_4(x, dlatents_in[:, 0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/content/StyleGAN2-TensorFlow-2.x/layers/synthesis_main_layer.py", line 37, in call
    x = self.mod_conv2d_layer(x, dlatent_vect)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/content/StyleGAN2-TensorFlow-2.x/layers/modulated_conv_2d_layer.py", line 91, in call
    x = tf.nn.conv2d(x, tf.cast(w, x.dtype), data_format='NHWC', strides=[1,1,1,1], padding='SAME')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1917, in conv2d_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 2014, in conv2d
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 937, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnimplementedError: The Conv2D op currently does not support grouped convolutions on the CPU. A grouped convolution was attempted to be run because the input depth of 1536 does not match the filter input depth of 512 [Op:Conv2D]
`

**Comment by sdtblck** [comment]
nvm - found the issue, on CPU you cannot use Zs with a batch size larger than one. 
Changed     

z = rnd.randn(3, 512).astype('float32')

to 

z = rnd.randn(1, 512).astype('float32')

and it runs fine. Maybe a note should be made somewhere about this error?

Closing issue since the problem is fixed

**Comment by rosasalberto** [comment]
Thanks @sdtblck ! I changed the example_how_to_use notebook and updated the readme.
